Update patch set 7
Patch Set 7:

Nvm, looks like the dataservices crash has to do with the 7.1 blobs or something, 06-18 13:57:00.836 15918 15918 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qti/dpm/DpmService;. Maybe we're missing some blobs

Patch-set: 7
Label: Verified=0