Update patch set 8
Patch Set 8: Code-Review-2

> > Nvm, looks like the dataservices crash has to do with the 7.1
 > blobs
 > > or something, 06-18 13:57:00.836 15918 15918 E AndroidRuntime:
 > > java.lang.NoClassDefFoundError: Failed resolution of:
 > > Lcom/qti/dpm/DpmService;. Maybe we're missing some blobs
 > 
 > Not sure what it's needed for but simply removing dpmserviceapp
 > from the build process fixes the fc without noticeable side
 > effects.

I don't think it's worth it to mess with anything outside of the GPS stack significantly. dpm is constantly crashing for me, and I think (but i'm not 100% sure) that i'm getting regressions in battery life with this, maybe as a result of dpm constantly crashing

Patch-set: 8
Reviewer: Paul Keith <11801@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=-2